# Generated by Django 5.1.4 on 2025-01-22 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=5)),
                ('anda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_de_Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=245)),
                ('cpf', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=25)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=254)),
                ('placa', models.CharField(max_length=10)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('obs', models.TextField(blank=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Moradore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=245)),
                ('cpf', models.CharField(max_length=25)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('telefone', models.CharField(max_length=25)),
                ('data_nascimento', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('obs', models.TextField(blank=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome_completo', models.CharField(max_length=254)),
                ('ocorrencia', models.TextField()),
                ('foto1', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('foto2', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_de_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_de_entrega', models.CharField(max_length=254)),
                ('codigo_de_rastreamento', models.CharField(blank=True, max_length=100)),
                ('destino', models.CharField(max_length=254)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs', models.TextField(blank=True)),
                ('foto_recebendo', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('foto_entrega', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
                ('horario_da_entrega', models.DateTimeField(blank=True, null=True)),
                ('quem_recebeu', models.CharField(blank=True, max_length=150)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_registro', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.apartamento')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
