# Generated by Django 5.1.4 on 2025-01-23 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_ocorrencia_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='numero_apartamento',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_evento', models.CharField(max_length=50)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('data_horas_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario_final_evento', models.CharField(max_length=25)),
                ('nomes_autorizados', models.TextField()),
                ('veiculos_autorizados', models.TextField()),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.apartamento')),
            ],
        ),
    ]
